### ISSUE TITLE
非交互式 (建议Demo使用) 的 BUG

### ISSUE THREAD

**Issue by shell-nlp** [iflytek/spark-ai-python#2]
```
Traceback (most recent call last):
  File "/home/dev/liuyu/project/llm-os/tests/test_spark_sdk.py", line 19, in <module>
    result = client.chat_in("你是谁")
  File "/home/dev/anaconda3/envs/langchain/lib/python3.10/site-packages/sparkai/socket_mode/websocket_client/__init__.py", line 459, in chat_in
    result = self.chat_outputer.merged_result
AttributeError: 'NoneType' object has no attribute 'merged_result'
```

**Comment by whybeyoung** [comment]
fix by new implement
