### ISSUE TITLE
sparkai.errors.SparkAIConnectionError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

### ISSUE THREAD

**Issue by jiegemena** [iflytek/spark-ai-python#28]
Traceback (most recent call last):
  File "d:\codehome\weixin\weixin\xfai.py", line 41, in <module>
    a = get_result("写一个交换代码")
  File "d:\codehome\weixin\weixin\xfai.py", line 35, in get_result
    a = spark.generate([messages], callbacks=[handler])
  File "D:\codehome\weixin\venv\lib\site-packages\sparkai\core\language_models\chat_models.py", line 412, in generate
    raise e
  File "D:\codehome\weixin\venv\lib\site-packages\sparkai\core\language_models\chat_models.py", line 402, in generate
    self._generate_with_cache(
  File "D:\codehome\weixin\venv\lib\site-packages\sparkai\core\language_models\chat_models.py", line 581, in _generate_with_cache
    return self._generate(
  File "D:\codehome\weixin\venv\lib\site-packages\sparkai\llm\llm.py", line 375, in _generate
    for content in self.client.subscribe(timeout=self.request_timeout):
  File "D:\codehome\weixin\venv\lib\site-packages\sparkai\llm\llm.py", line 691, in subscribe
    raise e
sparkai.errors.SparkAIConnectionError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

**Comment by whybeyoung** [comment]
这个问题是跟python安装环境缺少证书相关。
 你可以社区同学提供的方案:  https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
也许对你有用

**Comment by whybeyoung** [comment]
fixed by ignore ssl checking.
