### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by ykallan** [iflytek/spark-ai-python#30]
版本
```text
spark-ai-python==0.3.31 
```

调用代码
```python
# encoding: utf-8

from sparkai.llm.llm import ChatSparkLLM, ChunkPrintHandler
from sparkai.core.messages import ChatMessage

# 星火认知大模型Spark3.5 Max的URL值，其他版本大模型URL值请前往文档（https://www.xfyun.cn/doc/spark/Web.html）查看
SPARKAI_URL = 'wss://spark-api.xf-yun.com/v1.1/chat'
# 星火认知大模型调用秘钥信息，请前往讯飞开放平台控制台（https://console.xfyun.cn/services/bm35）查看
SPARKAI_APP_ID = '123'
SPARKAI_API_SECRET = '123'
SPARKAI_API_KEY = '123'
# 星火认知大模型Spark3.5 Max的domain值，其他版本大模型domain值请前往文档（https://www.xfyun.cn/doc/spark/Web.html）查看
SPARKAI_DOMAIN = 'general'


if __name__ == '__main__':
    spark = ChatSparkLLM(
        spark_api_url=SPARKAI_URL,
        spark_app_id=SPARKAI_APP_ID,
        spark_api_key=SPARKAI_API_KEY,
        spark_api_secret=SPARKAI_API_SECRET,
        spark_llm_domain=SPARKAI_DOMAIN,
        streaming=False,
    )
    messages = [ChatMessage(
        role="user",
        content='你好呀'
    )]
    handler = ChunkPrintHandler()
    a = spark.generate([messages], callbacks=[handler])
    print(a)


```

异常报错：
```text
Traceback (most recent call last):
  File "E:/PythonCodes/spark_lite/demo01.py", line 3, in <module>
    from sparkai.llm.llm import ChatSparkLLM, ChunkPrintHandler
  File "C:\ProgramData\Anaconda3\envs\fastapi\lib\site-packages\sparkai\llm\llm.py", line 20, in <module>
    from sparkai.core.callbacks import (
  File "C:\ProgramData\Anaconda3\envs\fastapi\lib\site-packages\sparkai\core\callbacks\__init__.py", line 13, in <module>
    from sparkai.core.callbacks.manager import (
  File "C:\ProgramData\Anaconda3\envs\fastapi\lib\site-packages\sparkai\core\callbacks\manager.py", line 39, in <module>
    from sparkai.core.messages import BaseMessage, get_buffer_string
  File "C:\ProgramData\Anaconda3\envs\fastapi\lib\site-packages\sparkai\core\messages\__init__.py", line 3, in <module>
    from sparkai.core.messages.ai import AIMessage, AIMessageChunk
  File "C:\ProgramData\Anaconda3\envs\fastapi\lib\site-packages\sparkai\core\messages\ai.py", line 10, in <module>
    class AIMessage(BaseMessage):
  File "pydantic\main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 451, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 550, in pydantic.fields.ModelField._type_analysis
  File "C:\ProgramData\Anaconda3\envs\fastapi\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

```

**Comment by bwl0211** [comment]
环境依赖可能有问题，可以尝试重新配置一个干净的环境。

**Comment by Eyict** [comment]
这是由python中的后端包的pydantic的兼容性问题引起的，再安装这个就可以了python -m pip install -U pydantic spacy。方法来自这篇博客https://blog.csdn.net/m0_43609475/article/details/131767811

**Comment by whybeyoung** [comment]
> 这是由python中的后端包的pydantic的兼容性问题引起的，再安装这个就可以了python -m pip install -U pydantic spacy。方法来自这篇博客https://blog.csdn.net/m0_43609475/article/details/131767811

验证的pydantic版本是多少， 1.0 和 2.0 好像差别很大
