### ISSUE TITLE
慢慢慢，经常30秒超时，讯飞的开放平台咋啦

### ISSUE THREAD

**Issue by try1995** [iflytek/spark-ai-python#36]
是不是官方没啥资源了，接口根本没法用，通过星火API调试中心里面调用还是很快的，使用自己的token就很拉跨

**Comment by imyizhang** [comment]
相同的问题

**Comment by whybeyoung** [comment]
您好，请参考文档中开启debug,然后提供下超时的请求日志里的sid.方便我们定位，thank you

**Comment by try1995** [comment]
> 您好，请参考文档中开启debug,然后提供下超时的请求日志里的sid.方便我们定位，thank you

您好，请问是这个吗？打开debug显示如下：
2024-06-29 03:20:32 UTC - SparkPythonSDK - DEBUG - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:598] - sid: cht000b689b@dx1906201f3ceb81d550, code: 0
2024-06-29 03:20:32 UTC - SparkPythonSDK - DEBUG - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:598] - sid: cht000b689b@dx1906201f3ceb81d550, code: 0
from bs4 import BeautifulSoup

{'run_id': UUID('f249396a-098f-4dcf-98df-df4ccf84a64d'), 'parent_run_id': None, 'tags': [], 'llm_output': {}, 'data': {'content': 'from bs4 import BeautifulSoup\n', 'role': 'assistant', 'index': 0}, 'final': False}
content='from bs4 import BeautifulSoup\n'

url = "https://www.baidu.com"

{'run_id': UUID('f249396a-098f-4dcf-98df-df4ccf84a64d'), 'parent_run_id': None, 'tags': [], 'llm_output': {}, 'data': {'content': '\nurl = "https://www.baidu.com"\n', 'role': 'assistant', 'index': 0}, 'final': False}
content='\nurl = "https://www.baidu.com"\n'
2024-06-29 03:21:02 UTC - SparkPythonSDK - ERROR - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:658] - SparkLLMClient wait LLM api response timeout 30 seconds
2024-06-29 03:21:32 UTC - SparkPythonSDK - ERROR - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:658] - SparkLLMClient wait LLM api response timeout 30 seconds

一般第一次正常，同样的第二次再调用就超时，稳定复现

**Comment by try1995** [comment]
> > 您好，请参考文档中开启debug,然后提供下超时的请求日志里的sid.方便我们定位，thank you
> 
> 您好，请问是这个吗？打开debug显示如下： 2024-06-29 03:20:32 UTC - SparkPythonSDK - DEBUG - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:598] - sid: cht000b689b@dx1906201f3ceb81d550, code: 0 2024-06-29 03:20:32 UTC - SparkPythonSDK - DEBUG - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:598] - sid: cht000b689b@dx1906201f3ceb81d550, code: 0 from bs4 import BeautifulSoup
> 
> {'run_id': UUID('f249396a-098f-4dcf-98df-df4ccf84a64d'), 'parent_run_id': None, 'tags': [], 'llm_output': {}, 'data': {'content': 'from bs4 import BeautifulSoup\n', 'role': 'assistant', 'index': 0}, 'final': False} content='from bs4 import BeautifulSoup\n'
> 
> url = "https://www.baidu.com"
> 
> {'run_id': UUID('f249396a-098f-4dcf-98df-df4ccf84a64d'), 'parent_run_id': None, 'tags': [], 'llm_output': {}, 'data': {'content': '\nurl = "[https://www.baidu.com"\n](https://www.baidu.com%22%5Cn)', 'role': 'assistant', 'index': 0}, 'final': False} content='\nurl = "[https://www.baidu.com"\n](https://www.baidu.com%22%5Cn)' 2024-06-29 03:21:02 UTC - SparkPythonSDK - ERROR - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:658] - SparkLLMClient wait LLM api response timeout 30 seconds 2024-06-29 03:21:32 UTC - SparkPythonSDK - ERROR - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:658] - SparkLLMClient wait LLM api response timeout 30 seconds
> 
> 一般第一次正常，同样的第二次再调用就超时，稳定复现

2024-06-29 03:21:02 UTC - SparkPythonSDK - ERROR - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:658] - SparkLLMClient wait LLM api response timeout 30 seconds
2024-06-29 03:21:32 UTC - SparkPythonSDK - ERROR - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:658] - SparkLLMClient wait LLM api response timeout 30 seconds
x`2024-06-29 03:22:02 UTC - SparkPythonSDK - ERROR - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:658] - SparkLLMClient wait LLM api response timeout 30 seconds
2024-06-29 03:22:32 UTC - SparkPythonSDK - ERROR - [/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py:658] - SparkLLMClient wait LLM api response timeout 30 seconds
Traceback (most recent call last):
  File "/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py", line 653, in a_subscribe
    content = self.queue.get(timeout=timeout)
  File "/root/miniforge3/envs/spark/lib/python3.10/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/appdata/sparkApi/streamspark.py", line 79, in <module>
    asyncio.run(test_astream())
  File "/root/miniforge3/envs/spark/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniforge3/envs/spark/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/appdata/sparkApi/streamspark.py", line 75, in test_astream
    async for message in a:
  File "/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/core/language_models/chat_models.py", line 309, in astream
    raise e
  File "/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/core/language_models/chat_models.py", line 293, in astream
    async for chunk in self._astream(
  File "/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py", line 280, in _astream
    async for content in self.client.a_subscribe(timeout=self.request_timeout):
  File "/root/miniforge3/envs/spark/lib/python3.10/site-packages/sparkai/llm/llm.py", line 661, in a_subscribe
    raise e
TimeoutError: SparkLLMClient wait LLM api response timeout 30 seconds

**Comment by whybeyoung** [comment]
可以在请求设置中适当 调整 request_timeout值 ，参考https://github.com/iflytek/spark-ai-python/tree/main?tab=readme-ov-file#%E6%96%B9%E5%BC%8F1-%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0
